apiVersion: v1
kind: PersistentVolume
metadata:
  name: match3-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s/match3-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: match3-postgres-pvc
  namespace: match3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: match3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match3-postgres
  template:
    metadata:
      labels:
        app: match3-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: match3-db-secret
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: match3-db-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: match3-db-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: match3-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: match3
spec:
  selector:
    app: match3-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
